Iter13
fasdalf/train-go-musthave-metrics pull request #13
Opened 2024-08-11 11:03 UTC by fasdalf

2024-08-17 07:47 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Ты реализовал доработки сервиса в соответствии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты консистентно встроил функционал в структуру существующего приложения. 👍
3. Ты реализовал тесты новых сценариев и дополнил существующие. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Мне кажется, по условию задачи DB сторадж должен работать так же, как и файловый в смысле синхронизации. Кажется, для DB реализовано только синхронное сохранение? Стоит реализовать асинхронное.
2. Не стоит возвращать конкретный тип ошибки. Стоит реализовать кастомную ошибку так, чтобы она реализовывала интерфейс error и возвращать его, а на вызывающей стороне можно будет использовать [[errors.As](http://errors.as/)](http://errors.as/)(...) для проверки.
3. По условию задачи *изменение в базе можно выполнять в рамках одной транзакции или одного запроса*, мне кажется, это условие не реализовано?

2024-08-17 07:47 UTC, vokinneberg commented on internal/common/jsonofflinestorage/jsonofflinestorage.go
> +	t.Stop()
То же самое - достаточно запутанная логика использования таймера.
```suggestion
	defer t.Stop()
```

2024-08-17 07:47 UTC, vokinneberg commented on cmd/agent/main.go
> +		go sendMetricsRoutine(context.TODO(), memStorage, address, sendInterval, retryer)
Тут можно передавать контекст из вне, например `WithCancel` и управлять жизненным циклом функций с его помощью, ведь зачем-то он в них передается?

2024-08-17 07:47 UTC, vokinneberg commented on cmd/server/main.go
> +	db := (*sql.DB)(nil)
Уже не первый раз вижу такую инициализацию переменных. Мне кажется, что это избыточно и достаточно определить переменную, как `var db *sql.DB` - в этом случае значением по умолчанию и так будет `nil`.

2024-08-17 07:47 UTC, vokinneberg commented on cmd/server/main.go
> +		err := error(nil)
То же самое.
```suggestion
		var err error
```

2024-08-17 07:47 UTC, vokinneberg commented on cmd/server/main.go
> +	if c.StorageFileName != "" && db == nil {
 Возможно стоит реализовать просто if/else?

2024-08-17 07:47 UTC, vokinneberg commented on cmd/server/main.go
> +			err := fileStorageService.SaverRoutine(savedChan)
Мне кажется, по условию задачи DB сторадж должен работать так же, как и файловый в смысле синхронизации. Кажется, для DB реализовано только синхронное сохранение? Стоит реализовать асинхронное.

2024-08-17 07:47 UTC, vokinneberg commented on internal/common/retryattempt/retryattempt.go
> +	tmr.Stop()
Вопрос - таймер от нуля, который еще и остановлен будет ли вообще тикать? 
```suggestion
	defer tmr.Stop()
```
Не заметил вызов `Reset(...)`. Мне кажется тут трудно разобраться в том, как таймер используется. Мы создаем таймер от нуля, останавливаем его, делаем ресет, останавливаем. Можно как-то упростить? Попробуй посмотреть в сторону `time.After(...)`.

2024-08-17 07:47 UTC, vokinneberg commented on internal/common/metricstorage/dbStorage.go
> +	tx, err := s.db.BeginTx(ctx, nil)
👍 за использование транзакции!

2024-08-17 07:47 UTC, vokinneberg commented on internal/common/metricstorage/dbStorage.go
> +	defer tx.Rollback()
Это стоит делать в случае ошибки, иначе произойдет не запланированный вызов `Rollback(...)`  во время выхода из функции. Думаю мы не хотим такого поведения, даже если перед этим был вызван `Commit(...)`.

2024-08-17 07:47 UTC, vokinneberg commented on internal/common/metricstorage/modelStorage.go
> +		s.UpdateGauge(metric.ID, *metric.Value)
По условию задачи _изменение в базе можно выполнять в рамках одной транзакции или одного запроса_, мне кажется эту условие не реализовано?

2024-08-17 07:47 UTC, vokinneberg commented on internal/server/handlers/saveMetricsHandler.go
> +	if errors.As(err, &pgErr); pgErr != nil && pgerrcode.IsConnectionException(pgErr.Code) {
Сработает ли это условие вообще когда-то, если у нас DB сторадж вообще не возвращает ошибок?

2024-08-17 17:33 UTC, fasdalf commented on internal/common/metricstorage/modelStorage.go
> +		s.UpdateGauge(metric.ID, *metric.Value)
`можно` это вам не `нужно`

2024-08-17 17:39 UTC, fasdalf commented on cmd/server/main.go
> +			err := fileStorageService.SaverRoutine(savedChan)
Подробные примеры с асинхронностью есть только перед 15 инкрементом. Если не будут гореть сроки - реализую там.

2024-08-17 18:20 UTC, fasdalf commented on cmd/server/main.go
> +	if c.StorageFileName != "" && db == nil {
тогда это будет elseif. "Ничто в мире не бывает более беспомощным, безответственным и порочным" чем цепочка elseif

2024-08-20 10:31 UTC, fasdalf commented on internal/common/jsonofflinestorage/jsonofflinestorage.go
> +	t.Stop()
++

2024-08-20 11:18 UTC, fasdalf commented on cmd/agent/main.go
> +		go sendMetricsRoutine(context.TODO(), memStorage, address, sendInterval, retryer)
++

2024-08-20 11:20 UTC, fasdalf commented on cmd/server/main.go
> +	db := (*sql.DB)(nil)
++

2024-08-20 11:20 UTC, fasdalf commented on cmd/server/main.go
> +		err := error(nil)
++

2024-08-20 11:30 UTC, fasdalf commented on cmd/server/main.go
> +	if c.StorageFileName != "" && db == nil {
тут нужна проверка на оба значения. А значит это будет elseif.
Ничто в мире не бывает более беспомощным, безответственным и порочным, [чем else if](https://neolurk.org/wiki/%D0%A1%D1%82%D0%B0%D1%80%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BF%D0%B8%D0%BF%D0%B0%D1%81%D1%82%D0%B0:%D0%A1%D1%82%D1%80%D0%B0%D1%85_%D0%B8_%D0%BD%D0%B5%D0%BD%D0%B0%D0%B2%D0%B8%D1%81%D1%82%D1%8C_%D0%B2_%D0%9B%D0%B0%D1%81-%D0%92%D0%B5%D0%B3%D0%B0%D1%81%D0%B5).

2024-08-20 11:31 UTC, fasdalf commented on cmd/server/main.go
> +	if c.StorageFileName != "" && db == nil {
++ пусть будет хотя бы switch (true)

2024-08-20 11:31 UTC, fasdalf commented on internal/common/retryattempt/retryattempt.go
> +	tmr.Stop()
++

2024-08-20 11:34 UTC, fasdalf commented on internal/common/metricstorage/dbStorage.go
> +	tx, err := s.db.BeginTx(ctx, nil)
🙇️

2024-08-20 11:39 UTC, fasdalf commented on internal/common/metricstorage/dbStorage.go
> +	defer tx.Rollback()
++

2024-08-22 09:51 UTC, fasdalf commented on internal/common/metricstorage/modelStorage.go
> +		s.UpdateGauge(metric.ID, *metric.Value)
Получился очень большой коммит, но ++

2024-08-22 09:51 UTC, fasdalf commented on internal/server/handlers/saveMetricsHandler.go
> +	if errors.As(err, &pgErr); pgErr != nil && pgerrcode.IsConnectionException(pgErr.Code) {
теперь возвращает ++

2024-08-22 15:15 UTC, fasdalf commented on internal/common/metricstorage/modelStorage.go
> +		s.UpdateGauge(metric.ID, *metric.Value)
И, конечно же, пришлось использовать теорию из будущих инкрементов.

2024-08-24 03:40 UTC, vokinneberg commented on internal/common/metricstorage/dbStorage.go
> +	defer tx.Rollback()
 Не откатится, но душа будет болеть от того, что сделали лишний вызов без причины 😊

2024-08-24 03:44 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением третьего спринта!  🎉  Отличная работа! 🚀

2024-08-25 12:33 UTC, merged