Iter5
fasdalf/train-go-musthave-metrics pull request #5
Opened 2024-07-03 21:27 UTC by fasdalf

2024-07-08 11:03 UTC, vokinneberg requested changes
Поздравляю с завершением Первого Спринта и первым ревью! 🤗 Твой код работает и проходит тесты, отличная работа! 🚀

**Сильные стороны твоего PR:**

1. **Модульность**: Код разделён на чёткие модули с хорошо разделёнными обязанностями.
2. **Функциональность:** Код функционален и корректен.

**Что можно улучшить:**

1. **Композиция компонентов и Dependency Injection.** Я рекомендую избавиться от глобальных переменных и попробовать инициализировать все зависимости в момент инициализации приложения.
2. **Не злоупотреблять вызовом логирования при помощи `fmt.Println(...)`**. Компоненты должны возвращать ошибки и давать возможность сервису корректно завершиться и вывести сообщение об ошибке в терминал. Лучше это делать при помощи `log.Printf(...)` или структурного логирования типа https://go.dev/blog/slog.
3. **Не стоит злоупотреблять использованием сторонних библиотек**, если от них нет явной пользы. На мой взгляд, использование стороннего мультиплексера типа gin обосновано, так как он сильно облегчает жизнь при работе с динамическими сегментами строки запроса, в то время как другие библиотеки можно использовать из стандартной библиотеки.
4. **Покрытие тестами**: Покрытие тестами можно улучшить, покрыть недостающие компоненты и добавить недостающие кейсы, а также добавить более информативные сообщения о том, что ожидалось и что пошло не так.
5. **Если ты используешь библиотеку gin** стоит обратить внимание на ее возможности по обработке ошибок и работе с  `gin.Context`.

2024-07-08 11:03 UTC, vokinneberg commented on internal/common/metricstorage/interface.go
> +type Storage interface {
Предлагаю рассмотреть вариант, при котором не будет определяться общий интерфейс в отдельном файле для работы с MemStorage, а интерфейс будет определяться рядом с кодом, который его использует. Таким образом, нам придется определить несколько более компактных интерфейсов, но наш код лучше будет соответствовать принципу Interface Segregation.

2024-07-08 11:03 UTC, vokinneberg commented on internal/common/metricstorage/memStorage.go
> +func NewMemStorage() Storage {
Не стоит возвращать тип интерфейса из фабричного метода. Так как Go использует duck typing, инстанс созданный `NewMemStorage()` уже будет реализовывать интерфейс если в нем реализованы соответствующие методы. 
```suggestion
func NewMemStorage() *MemStorage {
```

2024-07-08 11:03 UTC, vokinneberg commented on internal/common/metricstorage/memStorage.go
> +func (s *MemStorage) GetGauge(key string) float64 {
Предлагаю подумать, стоит ли возвращать ошибку в случае, если ключа нет в мапе? В этом случае будет возвращено значение по умолчанию для типа `int`, которое равно `0`. Нужно ли нам различать случаи, когда в MemStorage уже есть ключ, но значение равно `0`, и когда ключа нет? Это касается и других методов.

2024-07-08 11:03 UTC, vokinneberg commented on internal/common/metricstorage/memStorage.go
> +type MemStorage struct {
Предлагаю подумать, как код будет себя вести в случае конкурентного доступа? Могут ли возникнуть гонки? Нужна ли синхронизация?

2024-07-08 11:03 UTC, vokinneberg commented on internal/common/metricstorage/memStorage.go
> +func (s *MemStorage) UpdateCounter(key string, value int) {
На мой взгляд визуально было бы проще читать код, если бы методы были разделены пробелом. Так же было бы здорово, если бы были добавлены комментарии с описанием того, что делают публичные методы.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/config/config.go
> +var config *Config
Рекомендую отказаться от хранения глобального состояния и инициализации его на уровне пакета, посредством вызова `init(...)`. Это валидный инструмент в Go, но я бы не рекомендовал его использовать без необходимости, так как это может привести к проблемам при тестировании и сопровождении. Проще управлять жизненным циклом инстанса самостоятельно, создавая инстанс конфигурации либо в момент создания приложения (global), либо в момент обработки события или запроса (per request).
 Инициализировать Config можно в фабричном методе.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/config/config.go
> +	flag.IntVarP(&config.ReportInterval, "reportInterval", "r", defaultPollInterval, fmt.Sprintf("Report to server interval in seconds. Default is \"%d\"", defaultReportInterval))
Похоже тут опечатка в названии константы, которая используется по-умолчанию.
```suggestion
	flag.IntVarP(&config.ReportInterval, "reportInterval", "r", defaultReportInterval, fmt.Sprintf("Report to server interval in seconds. Default is \"%d\"", defaultReportInterval))
```

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/config/config.go
> +		fmt.Printf("%+v\n", err)
Глобально нет ничего плохого в том чтобы конфигурировать приложение при помощи переменных окружения, но я бы рекомендовал добавить к ошибке контекст и вместо того чтобы просто логировать вернуть ее вызывающему коду чтобы он принял решение о том, что делать с ошибкой.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/collectMetrics.go
> +/*
Рекомендую избегать закомментированных кусков кода, так как они значительно ухудшают читаемость. Если необходимо вернуться к старой версии файла, всегда можно воспользоваться историей в git.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/collectMetrics.go
> +	fmt.Println("Collecting metrics")
Советую избегать использования fmt.Println(...) для логирования и рассмотреть возможность использования логгера, например [slog](https://go.dev/blog/slog).

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/collectMetrics.go
> +	s.UpdateGauge("Alloc", float64(ms.Alloc))
Как мне кажется этот код можно переписать немного элегантнее, если вместо множественных вызовов `s.UpdateGauge(...)` определить мапу `map[string]float64` которую поместить списк метрик, а потом в цикле добавить из в  storage. Таким образом можно будет обновить только мапу, если нужно будет добавить новую метрику.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/collectMetrics_test.go
> +func TestCollectMetrics(t *testing.T) {
Предлагаю расширить список кейсов и проверить, что вызов `CollectMetrics(s)` приводит к сохранению всех ключей, которые мы ожидаем там видеть.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/sendMetrics.go
> +	fmt.Println("Sending metrics")
Советую избегать использования  ]fmt.Println(...)] для логирования и рассмотреть возможность использования логгера, например [slog](https://go.dev/blog/slog).

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/sendMetrics.go
> +var address = ``
Значение по умолчанию для стоки - пустая строка "". Нет необходимости инициализировать ее явно.
 
```suggestion
var address string
```

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/sendMetrics.go
> +		urls = append(urls, fmt.Sprintf(`%s%s/%s/%d`, address, constants.CounterStr, key, s.GetCounter(key)))
Можно сразу определить две константы:
```Go
const (
    URLTemplateCounter =  "http://%s/update/%s/%s/%d"
    URLTemplateGauge =  "http://%s/update/%s/%s/%d"
)
```
И использовать из, как шаблон для создания URL - таким образом можно избавиться от строки 16, тем более, что локальный переменная `address` переопределяет параметр функции `address`.

Так же предлагаю подумать можно ли оптимизировать `SendMetrics(...)`? Например, мы можем вынести код отправки метрики в отдельную функцию и вызывать ее вместо добавления созданного url в список.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/sendMetrics.go
> +			fmt.Println("Error sending metrics: ", err)
Думаю тут стоит добавить к ошибке контекст и вернуть ее вызывающему коду.

2024-07-08 11:03 UTC, vokinneberg commented on internal/agent/handlers/sendMetrics.go
> +		resp, err := client.R().Post(url)
Глобально не вижу ничего плохого в использовании библиотеки `resty`, но тот функционал, который тут используется доступен и в http клиенте из стандартной библиотеки.  Предлагаю полумать, какую пользу нам даем использование сторонней бибилиотеки?

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/config/config.go
> +var config *Config
екомендую отказаться от хранения глобального состояния и инициализации его на уровне пакета, посредством вызова init(...). Это валидный инструмент в Go, но я бы не рекомендовал его использовать без необходимости, так как это может привести к проблемам при тестировании и сопровождении. Проще управлять жизненным циклом инстанса самостоятельно, создавая инстанс конфигурации либо в момент создания приложения (global), либо в момент обработки события или запроса (per request).
 Инициализировать Config можно в фабричном методе.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/config/config.go
> +		fmt.Printf("%+v\n", err)
Я бы рекомендовал добавить к ошибке контекст и вместо того чтобы просто логировать вернуть ее вызывающему коду чтобы он принял решение о том, что делать с ошибкой.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +			http.Error(w, "GET requests only", http.StatusBadRequest)
Более подходящим кодом ответа тут мог бы быть `405 Method Not Allowed`.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +		_, _ = w.Write([]byte(fmt.Sprintf(pageTemplate, gauges, counters)))
Не стоит игнорировать ошибку.  Правильно будет ее обработать и вывести сообщение в консоль при помощи логирования.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +		fmt.Println("Processed OK")
Я бы рекомендовал использовать `log.Println(...)` или slog для структурного логирования, вместо `fmt.Println(...)`.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +	const (
Константы стоит вынести за пределы функции хендлера. Тот случай, когда из лучше определить глобально в пакете.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +			gauges += fmt.Sprintf(rowTemplate, key, fmt.Sprint(ms.GetGauge(key)))
Для конкатенации большого количества строк я бы рекомендовал использовать `strings.Builder`.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +		gauges := ""
Так же в принципе нет необходимости тут инициализировать строку значением по умолчанию.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/httpServer_test.go
> +			assert.Equal(t, tt.want.statusCode, w.Code, "Код ответа не совпадает с ожидаемым")
Разрабочики и сообщество Go не рекомендуют использовать сторонние библиотека для ассерта тестов, так как они либо останавливают тест рано (если assert вызывает t.Fatalf или panic), либо опускают интересную информацию о том, что тест сделал правильно. Это также заставляет пакет assert создавать совершенно новый суб-язык вместо повторного использования существующего языка программирования (самого Go). https://go.dev/wiki/TestComments

Так же я рекомендую добавить более информативные сообщения о том, что ожидалось и что пошло не так в тесты.

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/index.go
> +func NewIndexHandler(ms metricstorage.Storage) http.HandlerFunc {
Этот хендлер совсем не покрыт тестами?

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/updateMetric.go
> +	const indexValue = 2
Определение и инициализацию констант лучше вынести за пределы функции хендлера. 

```suggestion
const (
	  indexType = 0
	  indexName = 1
	  indexValue = 2
)
	
func NewUpdateMetricHandler(s metricstorage.Storage) http.HandlerFunc {
```

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/updateMetric.go
> +			path = path[1:]
При использовании gin можно обойтись без парсинга строки запроса и получать динамические сегменты при помощи встроенной функции:

```Go
c.Params.ByName("name")
```

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/updateMetric.go
> +		fmt.Println("Processing", r.Method, r.URL.Path)
Я бы рекомендовал использовать log.Println(...) или slog для структурного логирования, вместо fmt.Println(...).

2024-07-08 11:03 UTC, vokinneberg commented on internal/server/handlers/updateMetric.go
> +			http.Error(w, "POST requests only", http.StatusBadRequest)
Более подходящим кодом ответа тут мог бы быть `405 Method Not Allowed`.

2024-07-08 11:14 UTC, fasdalf commented on internal/common/metricstorage/memStorage.go
> +type MemStorage struct {
Могут, нужна, будет добавлена в слеуюдщих модулях.

2024-07-08 11:18 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +	const indexValue = 2
Ещё лучше преобразовать его в хендлер gin и использовать именованные параметры. Но для практики и погружения в стандартный пакет хендлер оставлен с типом из ядра. Константы с такими короткими именами должны же будут вызвать неудобства в других хендлерах из пакета рано или поздно?

2024-07-08 11:21 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +			path = path[1:]
в новом хендлере NewViewStatsHandler так и есть, здесь используется "совместимость с пакетом http" в учебных целях

2024-07-09 06:42 UTC, fasdalf commented on internal/common/metricstorage/interface.go
> +type Storage interface {
Получилось 2 интерфейса, причём разных - один потерял HasCounter() и HasGauge()

2024-07-09 06:42 UTC, fasdalf commented on internal/common/metricstorage/memStorage.go
> +func NewMemStorage() Storage {
++

2024-07-09 06:43 UTC, fasdalf commented on internal/common/metricstorage/memStorage.go
> +func (s *MemStorage) GetGauge(key string) float64 {
Изначально так и было, но отдельные HasCounter() и HasGauge() показались удобнее.

2024-07-09 06:46 UTC, fasdalf commented on internal/common/metricstorage/memStorage.go
> +func (s *MemStorage) UpdateCounter(key string, value int) {
Отступы ++
Комментарии к однострочникам - это перебор, добавлены комментарии к хендлерам.

2024-07-09 06:47 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +	const indexValue = 2
нет больше констант

2024-07-09 06:48 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +			path = path[1:]
++

2024-07-09 06:48 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +		fmt.Println("Processing", r.Method, r.URL.Path)
++

2024-07-09 06:48 UTC, fasdalf commented on internal/server/handlers/updateMetric.go
> +			http.Error(w, "POST requests only", http.StatusBadRequest)
++

2024-07-10 16:41 UTC, fasdalf commented on internal/server/handlers/index.go
> +func NewIndexHandler(ms metricstorage.Storage) http.HandlerFunc {
++

2024-07-17 20:52 UTC, vokinneberg commented on internal/server/handlers/updateMetric.go
> +	const indexValue = 2
Пока они используются внутри пакета я не вижу особых проблем, но в целом имена должны быть информативными в том контексте в котором они используются.

2024-07-17 20:57 UTC, vokinneberg approved these changes
Женя, привет 👋 Ты кажется не заметил некоторые мои комментарии, пройдись по ним пожалуйста еще раз. 🙏 В остальном я вижу, что твой код функционален, покрыт тестами и разбит на логические слои! Остальное мы сможем улучшить в последующих спринтах. 🦾  Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀

2024-07-18 07:08 UTC, merged