Iter9
fasdalf/train-go-musthave-metrics pull request #9
Opened 2024-07-24 15:50 UTC by fasdalf

2024-08-02 03:26 UTC, vokinneberg requested changes
Поздравляю с первым ревью второго спринта! 🤗 В этом спринте мы охватили большой и важный материал, а наше приложение усложнилось. 💪 В основном ты справился с реализацией, твое приложение проходит тесты и это здорово! Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и проходит тесты! 🚀

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Мне показалось, что твоя реализация сохранения метрик в файловое хранилище не совсем соответствует постановке задачи. В соответствии с постановкой необходимо реализовать сохранение метрик через интервал, установленный в переменной окружения, что предполагает некоторый джоб, который работает независимо от вызова API и сохраняет метрики в файл. В этом случае, если клиент отправляет метрики недостаточно часто, условие не выполнится.
2. Стоит убрать закомментированный код или, если этого нельзя избежать, добавить комментарии, поясняющие, почему он нужен. В противном случае лишний код загрязняет кодовую базу.
3. Стоит реализовать тесты получения метрик, как для старых ручек, так и для новой.

2024-08-02 03:26 UTC, vokinneberg commented on cmd/server/main.go
> +			panic(err)
Думаю упоминал на прошлом review, но вместо использования `panic` можно вызвать `log.Fatal(...)`, которая залогирует сообщение об ошибке и завершит процесс при помощи `os.Exit(1)`.

2024-08-02 03:26 UTC, vokinneberg commented on cmd/server/main.go
> +	fileStorage := jsonofflinestorage.NewJSONFileStorage(memStorage, c.StorageFileName, c.StorageFileRestore, c.StorageFileStoreInterval)
Если хочется убедиться в том, что метод `Save(...)` вызовется при выходе из main, можно воспользоваться `defer`.

```suggestion
	fileStorage := jsonofflinestorage.NewJSONFileStorage(memStorage, c.StorageFileName, c.StorageFileRestore, c.StorageFileStoreInterval)
	defer fileStorage.Save()
```

2024-08-02 03:26 UTC, vokinneberg commented on internal/server/handlers/checkMetricExistenceHandler.go
> +		// or just
Если ещё не упоминал - не стоит оставлять комментарии в коде, так как это замусоривает кодовую базу.

2024-08-02 03:26 UTC, vokinneberg commented on internal/server/httpServer.go
> +	ginCore.POST("/value/", handlers.CheckMetricExistenceHandler(ms), handlers.MetricValueResponseHandler(ms))
Мне кажется trailing slash можно опустить.

```suggestion
	ginCore.POST("/value", handlers.CheckMetricExistenceHandler(ms), handlers.MetricValueResponseHandler(ms))
```

2024-08-02 03:26 UTC, vokinneberg commented on internal/server/httpServer.go
>  	ginCore.Use(slogGin.New(slog.Default()))
Все-таки по условию задачи мы должны реализовать свой логирующий middleware.

2024-08-02 03:26 UTC, vokinneberg commented on internal/server/httpServer_test.go
> +			name: "NaN",
Стоит добавить тесты получения метрик.

2024-08-02 03:26 UTC, vokinneberg commented on internal/server/handlers/saveToFileHandler.go
> +		err := s.SaveWithInterval()
Мне кажется эта реализация не совсем соответствует постановке задачи. В соответствии с постановкой необходимо реализовать сохранение метрик через интервал, установленный в переменной окружения, что предполагает некоторый джоб, который работает независимо от вызова API и сохраняет метрики в файл. В этом случае, ели клиент отправляет метрики недостаточно часто, условие не выполнится.

2024-08-02 16:24 UTC, fasdalf commented on internal/server/handlers/saveToFileHandler.go
> +		err := s.SaveWithInterval()
Теперь, в 3 спринте, я вижу как можно сделать сохранение после каждого изменения метрики (если в интервале стоит 0) или по тикеру, или по подписке на системный сигнал. Тогда не вызывать сохранение если ничего не изменилось казалось хорошей идеей.

2024-08-02 16:42 UTC, fasdalf commented on internal/server/handlers/saveToFileHandler.go
> +		err := s.SaveWithInterval()
П.С. Разве отдельный джоб без синхронизации потоков (которую мы ещё официально не прошли) не будет выстрелом себе в ногу?

2024-08-03 12:34 UTC, fasdalf commented on cmd/server/main.go
> +	fileStorage := jsonofflinestorage.NewJSONFileStorage(memStorage, c.StorageFileName, c.StorageFileRestore, c.StorageFileStoreInterval)
Сигнал всё равно надо перехватывать и останавливать ХТТП сервер, иначе defer не отрабатывает.

2024-08-03 12:35 UTC, fasdalf commented on cmd/server/main.go
> +			panic(err)
ДОбавлено структурированнное логирование перед паникой.

2024-08-03 12:37 UTC, fasdalf commented on internal/server/handlers/checkMetricExistenceHandler.go
> +		// or just
Комментарии заменены на человекопнятные.
Замечание распространяется на "закомментированный код" или на любые комментарии кроме документации над объявлением функции?

2024-08-03 12:38 UTC, fasdalf commented on internal/server/httpServer.go
> +	ginCore.POST("/value/", handlers.CheckMetricExistenceHandler(ms), handlers.MetricValueResponseHandler(ms))
оказалось можно

2024-08-03 12:38 UTC, fasdalf commented on internal/server/httpServer.go
>  	ginCore.Use(slogGin.New(slog.Default()))
добавлено

2024-08-04 08:10 UTC, fasdalf commented on internal/server/httpServer.go
>  	ginCore.Use(slogGin.New(slog.Default()))
++

2024-08-04 08:22 UTC, fasdalf commented on internal/server/httpServer.go
> +	ginCore.POST("/value/", handlers.CheckMetricExistenceHandler(ms), handlers.MetricValueResponseHandler(ms))
++

2024-08-04 11:39 UTC, fasdalf commented on internal/server/httpServer_test.go
> +			name: "NaN",
Добавленео

2024-08-08 03:52 UTC, vokinneberg commented on cmd/server/main.go
> +			panic(err)
Действительно, если нужно чтобы отработали `defer` вызовы, panic подходит лучше.

2024-08-08 03:57 UTC, vokinneberg commented on internal/server/handlers/checkMetricExistenceHandler.go
> +		// or just
Лично мне не нравится вообще любой закомментированный код и я стараюсь избегать его и в рабочих проектах тоже. Тут работает теория разбитых окон - как только появляется закоментированный кусочек в кодовой базе, будет появляться еще и еще. Практика показывает, что в 99% случаев эти комментарии ни как не используются и остаются жить в коде вечно. В 1% случаев, если действительно закомментированный код нужен стоит добавить комментарий для чего именно он был оставлен.

2024-08-08 04:01 UTC, vokinneberg commented on internal/server/handlers/saveToFileHandler.go
> +		err := s.SaveWithInterval()
Ну все зависит от реализации 😊   На мой взгляд можно реализовать условие задачи теми средствами, которые предлагаются на данном этапе. Ну давай оставим вопрос до 3 спринта 👍

2024-08-08 04:03 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью второго спринта! 🤗  У нас остался открытый вопрос относительно синхронной записи, я предлагаю обсудить его на 3 спринте. Думаю полезно было бы запланировать встречу 1 на 1, где мы могли бы это обсудить 🤝

2024-08-11 12:00 UTC, merged